(function(){
'use strict';

const E={
  squat:{name:'Присед к стулу',focus:'Ноги · ягодицы',dose:'3 × 12',steps:['Встань перед устойчивым стулом, стопы примерно на ширине плеч.','Уведи таз назад, как будто садишься; колени направляй по линии носков.','Легко коснись стула ягодицами и встань, давя всей стопой в пол.'],tip:'Не падай на стул и не своди колени внутрь.',feel:'Бёдра и ягодицы.'},
  sumo:{name:'Присед сумо',focus:'Ягодицы · внутренняя поверхность бедра',dose:'3 × 12',steps:['Поставь стопы шире плеч, носки немного разверни наружу.','Опускай таз вниз и назад, колени веди по направлению носков.','Встань через всю стопу и мягко сожми ягодицы.'],tip:'Не заваливайся на внутренний край стоп.',feel:'Ягодицы и внутреннюю поверхность бёдер.'},
  reverseLunge:{name:'Выпад назад с опорой',focus:'Ноги · ягодицы',dose:'3 × 8 / ногу',steps:['Встань рядом со стулом или стеной и держись рукой.','Сделай шаг назад и опусти заднее колено вниз в комфортной амплитуде.','Нажми передней стопой в пол и вернись в стойку.'],tip:'Переднее колено не заваливай внутрь; глубина не обязательна.',feel:'Ягодицу и бедро передней ноги.'},
  stepUp:{name:'Шаг на невысокую ступень',focus:'Ноги · ягодицы',dose:'3 × 10 / ногу',steps:['Поставь всю стопу рабочей ноги на устойчивую невысокую ступень.','Перенеси вес на неё и немного наклони корпус вперёд.','Поднимись усилием рабочей ноги и медленно спустись.'],tip:'Не отталкивайся сильно нижней ногой.',feel:'Ягодицу и переднюю поверхность бедра.'},
  hinge:{name:'Румынская тяга с бутылками',focus:'Ягодицы · задняя поверхность бедра',dose:'3 × 12',steps:['Держи бутылки перед бёдрами, колени слегка согнуты.','Отведи таз назад, ведя бутылки близко к ногам; спина остаётся длинной.','Почувствовав натяжение под ягодицами, вернись вверх за счёт ягодиц.'],tip:'Это движение тазом назад, а не присед.',feel:'Ягодицы и заднюю поверхность бёдер.'},
  bridge:{name:'Ягодичный мост',focus:'Ягодицы',dose:'3 × 15',steps:['Ляг на спину, согни колени и поставь стопы ближе к тазу.','На выдохе прижми стопы к полу и подними таз.','Сожми ягодицы на секунду и плавно опусти таз.'],tip:'Не поднимай таз за счёт сильного прогиба поясницы.',feel:'Ягодицы.'},
  bridgePause:{name:'Ягодичный мост с паузой',focus:'Ягодицы',dose:'3 × 12',steps:['Подними таз в обычный ягодичный мост.','Задержись в верхней точке на 2 секунды, сохраняя рёбра собранными.','Медленно опусти таз и повтори.'],tip:'Пауза должна чувствоваться в ягодицах, не в пояснице.',feel:'Ягодицы.'},
  clam:{name:'Ракушка лёжа на боку',focus:'Средняя ягодичная',dose:'3 × 15 / сторону',steps:['Ляг на бок, согни колени примерно под 90°, стопы вместе.','Не двигая таз, подними верхнее колено.','Остановись до того, как таз начнёт откатываться назад, и медленно закрой колени.'],tip:'Таз не вращай назад.',feel:'Боковую часть ягодицы.'},
  sideLeg:{name:'Подъём прямой ноги лёжа на боку',focus:'Средняя ягодичная',dose:'3 × 12 / сторону',steps:['Ляг на бок, нижнюю ногу можно согнуть.','Верхнюю ногу вытяни, носок направь вперёд.','Подними ногу на 30–40° и медленно опусти.'],tip:'Не разворачивай таз назад и не задирай ногу слишком высоко.',feel:'Боковую часть ягодицы.'},
  kickBack:{name:'Отведение ноги назад стоя',focus:'Ягодицы',dose:'3 × 12 / ногу',steps:['Держись за стул и слегка наклони корпус вперёд.','Собери живот и сохрани таз ровным.','Отведи ногу назад без прогиба поясницы и плавно верни.'],tip:'Амплитуда небольшая; движение идёт от тазобедренного сустава.',feel:'Ягодицу рабочей ноги.'},
  calf:{name:'Подъёмы на носки',focus:'Икры',dose:'3 × 18',steps:['Встань ровно и держись за опору.','Медленно поднимись на носки как можно выше без завала стоп.','Задержись на секунду и медленно опусти пятки.'],tip:'Не раскачивайся и не спеши.',feel:'Икроножные мышцы.'},
  wallSit:{name:'Статический стул у стены',focus:'Бёдра · ягодицы',dose:'3 × 25 сек',steps:['Прижмись спиной к стене и поставь стопы немного впереди.','Скользи вниз до комфортной глубины.','Удерживай положение, колени держи по линии стоп.'],tip:'Не обязательно опускаться до угла 90°.',feel:'Переднюю поверхность бёдер.'},
  push:{name:'Отжимания от стола',focus:'Грудь · трицепс',dose:'3 × 8–12',steps:['Поставь ладони на устойчивый стол чуть шире плеч.','Отойди ногами назад и выстрой тело одной линией.','Согни локти примерно под 45° и опусти грудь к опоре, затем выжми себя вверх.'],tip:'Не провисай в пояснице. Чем выше опора, тем легче.',feel:'Грудь и заднюю поверхность рук.'},
  row:{name:'Тяга бутылок к поясу',focus:'Спина · руки',dose:'3 × 12',steps:['Слегка наклони корпус вперёд с нейтральной спиной.','Опусти руки вниз и плечи подальше от ушей.','Потяни локти назад к поясу, сведи лопатки и медленно распрями руки.'],tip:'Не делай рывок корпусом.',feel:'Мышцы между лопатками.'},
  shoulderPress:{name:'Жим бутылок вверх',focus:'Плечи · руки',dose:'3 × 10',steps:['Держи бутылки у плеч, корпус устойчивый.','Подтяни живот и не выпячивай рёбра.','Выжми руки вверх и плавно верни к плечам.'],tip:'Не прогибай поясницу и не зажимай шею.',feel:'Плечи и трицепс.'},
  lateralRaise:{name:'Разведение рук в стороны',focus:'Плечи',dose:'2 × 12',steps:['Возьми очень лёгкие бутылки, локти чуть согни.','Подними руки в стороны примерно до уровня плеч.','Медленно опусти руки.'],tip:'Лучше меньший вес и чистая техника.',feel:'Боковую часть плеч.'},
  curl:{name:'Сгибание рук с бутылками',focus:'Бицепс',dose:'3 × 12',steps:['Встань ровно, локти прижми к бокам.','Согни руки и подними бутылки к плечам.','Медленно опусти, сохраняя локти на месте.'],tip:'Не раскачивай корпус.',feel:'Переднюю поверхность рук.'},
  triceps:{name:'Разгибание рук назад в наклоне',focus:'Трицепс',dose:'3 × 12',steps:['Наклонись вперёд, локти согни и прижми к корпусу.','Не двигая плечом, выпрями предплечья назад.','Сожми трицепс и медленно снова согни локти.'],tip:'Движение только в локтях.',feel:'Заднюю поверхность рук.'},
  wallSlide:{name:'Скольжение руками по стене',focus:'Лопатки · плечи',dose:'3 × 10',steps:['Встань спиной к стене, стопы чуть впереди.','Согни локти и мягко прижми руки к стене насколько комфортно.','Скользи руками вверх, не поднимая плечи, затем вернись.'],tip:'Не выгибай поясницу ради большей амплитуды.',feel:'Лопатки и плечи.'},
  chinTuck:{name:'Подбородок назад у стены',focus:'Шея · осанка',dose:'3 × 10',steps:['Встань затылком к стене или сядь ровно.','Не опуская подбородок вниз, мягко смести голову назад.','Задержись на 2 секунды и расслабь.'],tip:'Не дави затылком сильно в стену.',feel:'Глубокие мышцы шеи.'},
  deadbug:{name:'Dead bug',focus:'Глубокий кор',dose:'3 × 8 / сторону',steps:['Ляг на спину, ноги согнуты над тазом, руки вверх.','На выдохе мягко подтяни низ живота и стабилизируй поясницу.','Медленно опускай противоположные руку и ногу, затем вернись и поменяй сторону.'],tip:'Если поясница отрывается, уменьши амплитуду.',feel:'Глубокое напряжение живота.'},
  heelTap:{name:'Касание пяток лёжа',focus:'Косые мышцы живота',dose:'3 × 14 / сторону',steps:['Ляг на спину, стопы близко к ягодицам, лопатки слегка приподняты.','Потянись правой рукой к правой пятке.','Вернись в центр и потянись левой рукой к левой пятке.'],tip:'Движение короткое, шея расслаблена.',feel:'Боковые мышцы живота.'},
  reverseCrunch:{name:'Обратное подкручивание таза',focus:'Низ живота',dose:'3 × 10',steps:['Ляг на спину, ноги согнуты над тазом.','На выдохе слегка подтяни колени к груди и приподними таз на 1–2 см.','Медленно верни таз на пол без раскачки.'],tip:'Не делай мах ногами.',feel:'Нижнюю часть пресса.'},
  heelSlide:{name:'Скольжение пяткой',focus:'Низ живота',dose:'3 × 10 / ногу',steps:['Ляг на спину, обе стопы на полу.','На выдохе мягко собери низ живота.','Медленно выпрямляй одну ногу, скользя пяткой по полу, затем верни.'],tip:'Если поясница прогибается, сократи длину скольжения.',feel:'Глубокий низ живота.'},
  sidePlank:{name:'Боковая планка с колен',focus:'Косые мышцы · боковая линия',dose:'2 × 25 сек / сторону',steps:['Ляг на бок, опора на предплечье, колени согнуты.','Подними таз, чтобы плечо, таз и колени образовали одну линию.','Дыши спокойно и удерживай положение.'],tip:'Локоть держи под плечом.',feel:'Боковую часть корпуса.'},
  crossCrunch:{name:'Колено к противоположному локтю стоя',focus:'Пресс · координация',dose:'3 × 12 / сторону',steps:['Встань ровно, руки у висков.','Подними колено и мягко поверни грудную клетку к нему противоположным локтем.','Вернись в стойку и повтори другой стороной.'],tip:'Не тяни шею и не гонись за скоростью.',feel:'Косые мышцы живота.'},
  birdDog:{name:'Bird dog',focus:'Кор · спина',dose:'3 × 8 / сторону',steps:['Встань на четвереньки, ладони под плечами.','Вытяни противоположные руку и ногу в разные стороны.','Задержись на секунду, сохраняя таз ровным, затем вернись.'],tip:'Тянись в длину, а не вверх.',feel:'Кор и мышцы вдоль позвоночника.'},
  catCow:{name:'Кошка-корова',focus:'Позвоночник',dose:'2 × 8',steps:['Встань на четвереньки.','На вдохе мягко раскрой грудную клетку и направь копчик назад.','На выдохе округли спину от таза к голове.'],tip:'Не запрокидывай голову резко.',feel:'Движение вдоль всего позвоночника.'},
  child:{name:'Поза ребёнка',focus:'Спина · дыхание',dose:'60 сек',steps:['Опусти таз к пяткам и колени разведи настолько, насколько удобно.','Вытяни руки вперёд или положи вдоль тела.','Расслабь лоб и дыши в заднюю поверхность рёбер.'],tip:'Подложи подушку под таз или лоб, если так комфортнее.',feel:'Расслабление спины.'},
  dog:{name:'Собака мордой вниз',focus:'Спина · ноги',dose:'2 × 30 сек',steps:['Из положения на четвереньках подними таз вверх и назад.','Согни колени настолько, чтобы спина оставалась длинной.','Толкай ладонями пол и направляй грудь к бёдрам.'],tip:'Прямые колени не цель.',feel:'Спину и заднюю поверхность ног.'},
  lowLunge:{name:'Низкий выпад',focus:'Таз · сгибатели бедра',dose:'2 × 30 сек / сторону',steps:['Из положения на четвереньках поставь стопу между ладонями.','Опусти заднее колено на коврик и выпрями корпус.','Мягко направляй таз вперёд, сохраняя рёбра над тазом.'],tip:'Не проваливайся в поясницу.',feel:'Переднюю поверхность бедра задней ноги.'},
  twist:{name:'Скрутка лёжа',focus:'Спина · бока',dose:'2 × 40 сек / сторону',steps:['Ляг на спину, согни колени.','Опусти оба колена в одну сторону, руки разведи.','Плечи оставь тяжёлыми на полу и дыши спокойно.'],tip:'Уменьши амплитуду, если неприятно в пояснице.',feel:'Бока и поясницу.'},
  pilatesBreath:{name:'Пилатес-дыхание в рёбра',focus:'Дыхание · кор',dose:'90 сек',steps:['Ляг на спину, ладони положи на нижние рёбра.','На вдохе направляй воздух в стороны и назад в рёбра.','На длинном выдохе мягко подтяни низ живота, не напрягая шею.'],tip:'Плечи и лицо остаются расслабленными.',feel:'Глубокий кор.'},
  toeTap:{name:'Toe taps по одной ноге',focus:'Глубокий кор',dose:'3 × 8 / ногу',steps:['Подними ноги в положение 90/90.','Сохраняя таз неподвижным, опусти носок одной ноги к полу.','Верни ногу и повтори другой.'],tip:'Если спина прогибается, касайся пола раньше.',feel:'Низ живота.'},
  pilatesBridge:{name:'Пилатес-мост с артикуляцией',focus:'Ягодицы · позвоночник',dose:'3 × 10',steps:['На выдохе слегка подкрути таз.','Поднимай таз постепенно, будто отрываешь позвоночник от коврика по одному позвонку.','Так же медленно опускайся обратно.'],tip:'Не поднимай таз слишком высоко.',feel:'Ягодицы и заднюю линию.'},
  swimming:{name:'Swimming облегчённый',focus:'Спина · ягодицы',dose:'3 × 20 сек',steps:['Ляг на живот, лоб положи на сложенное полотенце.','Поочерёдно слегка приподнимай противоположные руку и ногу.','Двигайся медленно, вытягиваясь в длину.'],tip:'Не запрокидывай голову и не поднимай конечности высоко.',feel:'Спину и ягодицы.'},
  mermaid:{name:'Mermaid сидя',focus:'Боковая линия · дыхание',dose:'2 × 30 сек / сторону',steps:['Сядь удобно, ноги согни так, как комфортно.','Подними одну руку вверх и потянись корпусом в противоположную сторону.','Дыши в раскрытый бок и затем смени сторону.'],tip:'Не скручивайся вперёд.',feel:'Мягкое вытяжение бока.'},
  swan:{name:'Swan prep',focus:'Грудной отдел · спина',dose:'3 × 8',steps:['Ляг на живот, ладони возле плеч.','Вытяни макушку вперёд и слегка приподними грудь.','Опустись, сохраняя плечи далеко от ушей.'],tip:'Подъём небольшой, таз остаётся на полу.',feel:'Грудной отдел и верх спины.'},
  mountainBreath:{name:'Дыхание в позе горы',focus:'Дыхание · осанка',dose:'60 сек',steps:['Встань ровно, стопы устойчиво на полу.','Вытяни макушку вверх, плечи опусти.','Сделай 5–6 спокойных вдохов и длинных выдохов через нос.'],tip:'Не напрягай колени и челюсть.',feel:'Устойчивость и спокойное дыхание.'},
  warrior2:{name:'Воин II мягкий',focus:'Ноги · таз',dose:'2 × 30 сек / сторону',steps:['Поставь ноги широко, переднюю стопу разверни вперёд.','Согни переднее колено, задняя нога остаётся прямой.','Разведи руки в стороны и смотри поверх передней ладони.'],tip:'Переднее колено направлено по линии стопы.',feel:'Ноги, таз и плечи.'},
  puppy:{name:'Поза щенка',focus:'Плечи · грудной отдел',dose:'2 × 30 сек',steps:['Из положения на четвереньках оставь таз над коленями.','Шагни ладонями вперёд и опусти грудь ближе к полу.','Лоб можно положить на подушку и спокойно дышать.'],tip:'Не проваливай поясницу.',feel:'Плечи и грудной отдел.'},
  thread:{name:'Нитка в иголку',focus:'Грудной отдел · лопатки',dose:'2 × 30 сек / сторону',steps:['С четверенек проведи одну руку под другой ладонью.','Опусти плечо и бок головы на коврик.','Дыши в верхнюю часть спины, затем вернись и смени сторону.'],tip:'Таз остаётся примерно над коленями.',feel:'Область между лопатками.'},
  figure4:{name:'Figure-4 лёжа',focus:'Ягодицы · таз',dose:'2 × 45 сек / сторону',steps:['Ляг на спину, положи голень одной ноги на бедро другой.','Подтяни опорную ногу к себе за заднюю поверхность бедра.','Расслабь плечи и спокойно дыши.'],tip:'Не дави рукой на колено скрещенной ноги.',feel:'Ягодицу и наружную поверхность бедра.'},
  march:{name:'Бодрый марш на месте',focus:'Кардио · всё тело',dose:'3 × 60 сек',steps:['Встань ровно и начни шагать на месте.','Добавь активную работу согнутыми руками.','Поднимай колени до комфортной высоты и держи устойчивый темп.'],tip:'Темп должен позволять говорить короткими фразами.',feel:'Умеренное повышение пульса.'},
  stepTouch:{name:'Step-touch с руками',focus:'Кардио · ноги',dose:'3 × 45 сек',steps:['Шагни вправо и приставь левую стопу.','Одновременно подними руки вперёд или вверх.','Продолжай из стороны в сторону без прыжков.'],tip:'Стопы ставь мягко.',feel:'Пульс и работу ног.'},
  boxing:{name:'Бокс стоя',focus:'Кардио · руки',dose:'3 × 45 сек',steps:['Поставь одну ногу немного впереди, кулаки держи у подбородка.','Поочерёдно выпрямляй руки вперёд, слегка поворачивая корпус.','Каждую руку возвращай обратно к лицу.'],tip:'Не разгибай локоть до жёсткой блокировки.',feel:'Плечи, руки и пульс.'},
  skater:{name:'Конькобежец шагом',focus:'Кардио · ягодицы',dose:'3 × 45 сек',steps:['Сделай широкий шаг вправо и перенеси на него вес.','Левую ногу отведи назад по диагонали без прыжка.','Перейди широким шагом в другую сторону.'],tip:'Колено опорной ноги держи мягким.',feel:'Ягодицы и пульс.'},
  shoulderCircles:{name:'Круги плечами',focus:'Плечи',dose:'2 × 8 / направление',steps:['Встань или сядь ровно.','Подними плечи вверх, отведи назад, опусти и верни вперёд.','Сделай круги в обе стороны.'],tip:'Двигайся медленно и не проходи через боль.',feel:'Плечевой пояс.'},
  ankleWall:{name:'Голеностоп у стены',focus:'Голеностоп',dose:'2 × 10 / ногу',steps:['Поставь носок в нескольких сантиметрах от стены.','Не отрывая пятку, направь колено вперёд к стене.','Вернись и повтори.'],tip:'Колено идёт по линии второго-третьего пальца стопы.',feel:'Подвижность голеностопа.'},
  chestStretch:{name:'Раскрытие груди у стены',focus:'Грудь · плечи',dose:'2 × 30 сек / сторону',steps:['Поставь ладонь или предплечье на стену.','Медленно поверни корпус от стены.','Остановись при мягком растяжении и спокойно дыши.'],tip:'Не выкручивай плечо через боль.',feel:'Грудные мышцы.'},
  pelvicBreath:{name:'Диафрагмальное дыхание',focus:'Дыхание · тазовое дно',dose:'2 мин',steps:['Ляг или сядь удобно, расслабь живот и ягодицы.','На вдохе позволь рёбрам расшириться, а тазовому дну мягко расслабиться.','На выдохе почувствуй естественный лёгкий подъём тазового дна без сильного сжатия.'],tip:'Не втягивай живот резко и не задерживай дыхание.',feel:'Связь дыхания и тазового дна.'},
  pelvicLift:{name:'Мягкий лифт тазового дна',focus:'Тазовое дно',dose:'2 × 6',steps:['На вдохе полностью расслабь область тазового дна.','На выдохе мягко собери мышцы примерно на 30–40% усилия.','Удержи 2–3 секунды и полностью расслабь на вдохе.'],tip:'Не тренируйся во время мочеиспускания и не сжимай ягодицы.',feel:'Небольшой внутренний подъём.'}
};

const W={
  STRENGTH:{title:'Силовая · всё тело A',duration:'30–35 мин',tone:'Сила и тонус',category:'strength',level:'Средняя',items:['squat','push','hinge','row','bridge','deadbug']},
  STRENGTH_B:{title:'Силовая · всё тело B',duration:'28–34 мин',tone:'Сила без прыжков',category:'strength',level:'Средняя',items:['stepUp','shoulderPress','reverseLunge','lateralRaise','bridgePause','sidePlank']},
  LOWER:{title:'Ноги и ягодицы A',duration:'26–32 мин',tone:'Низ тела',category:'strength',level:'Средняя',items:['sumo','reverseLunge','bridgePause','kickBack','calf','wallSit']},
  LOWER_B:{title:'Ноги и ягодицы B',duration:'24–30 мин',tone:'Форма ног',category:'strength',level:'Средняя',items:['hinge','stepUp','clam','sideLeg','sumo','calf']},
  UPPER:{title:'Руки, плечи и спина A',duration:'22–28 мин',tone:'Верх тела',category:'strength',level:'Средняя',items:['push','row','shoulderPress','curl','triceps','lateralRaise']},
  UPPER_B:{title:'Руки и осанка B',duration:'20–26 мин',tone:'Плечи и лопатки',category:'strength',level:'Лёгкая–средняя',items:['wallSlide','row','shoulderPress','lateralRaise','curl','chinTuck']},
  GLUTES:{title:'Ягодицы A · тонус',duration:'22–28 мин',tone:'Ягодицы и бёдра',category:'strength',level:'Средняя',items:['bridgePause','sideLeg','hinge','kickBack','sumo','clam']},
  GLUTES_B:{title:'Ягодицы B · бок и верх',duration:'20–26 мин',tone:'Форма ягодиц',category:'strength',level:'Средняя',items:['clam','sideLeg','stepUp','bridge','kickBack','wallSit']},
  CORE:{title:'Кор · стабильность',duration:'18–24 мин',tone:'Глубокий кор',category:'core',level:'Средняя',items:['deadbug','birdDog','heelSlide','sidePlank','bridge','crossCrunch']},
  ABS:{title:'Пресс A · без прыжков',duration:'16–22 мин',tone:'Живот',category:'core',level:'Средняя',items:['heelTap','deadbug','reverseCrunch','sidePlank','crossCrunch','heelSlide']},
  ABS_LOWER:{title:'Пресс B · низ живота',duration:'14–20 мин',tone:'Низ живота',category:'core',level:'Лёгкая–средняя',items:['heelSlide','toeTap','reverseCrunch','deadbug','bridge','sidePlank']},
  ABS_WAIST:{title:'Пресс C · талия и косые',duration:'15–21 мин',tone:'Талия и боковая линия',category:'core',level:'Средняя',items:['heelTap','sidePlank','crossCrunch','twist','deadbug','birdDog']},
  PILATES:{title:'Пилатес A · всё тело',duration:'22–28 мин',tone:'Контроль и тонус',category:'pilates',level:'Лёгкая–средняя',items:['pilatesBreath','toeTap','pilatesBridge','sideLeg','swimming','mermaid']},
  PILATES_CORE:{title:'Пилатес B · кор',duration:'18–24 мин',tone:'Глубокий кор',category:'pilates',level:'Лёгкая–средняя',items:['pilatesBreath','toeTap','deadbug','heelSlide','sidePlank','mermaid']},
  PILATES_LOWER:{title:'Пилатес C · ноги и ягодицы',duration:'20–26 мин',tone:'Низ тела · контроль',category:'pilates',level:'Средняя',items:['pilatesBridge','clam','sideLeg','sumo','bridgePause','figure4']},
  PILATES_POSTURE:{title:'Пилатес D · осанка',duration:'18–23 мин',tone:'Спина и осанка',category:'pilates',level:'Лёгкая',items:['pilatesBreath','swan','swimming','birdDog','wallSlide','mermaid']},
  YOGA:{title:'Йога A · мягкий поток',duration:'18–24 мин',tone:'Гибкость и дыхание',category:'yoga',level:'Лёгкая',items:['mountainBreath','catCow','dog','lowLunge','warrior2','child']},
  YOGA_EVENING:{title:'Йога B · вечерняя',duration:'15–20 мин',tone:'Расслабление',category:'yoga',level:'Очень лёгкая',items:['pilatesBreath','figure4','twist','lowLunge','child','mountainBreath']},
  YOGA_BACK:{title:'Йога C · спина и плечи',duration:'16–22 мин',tone:'Спина и плечи',category:'yoga',level:'Лёгкая',items:['catCow','puppy','thread','swan','dog','child']},
  YOGA_HIPS:{title:'Йога D · таз и бёдра',duration:'18–24 мин',tone:'Мобильность таза',category:'yoga',level:'Лёгкая',items:['figure4','lowLunge','sumo','twist','child','dog']},
  BACK:{title:'Здоровая спина',duration:'18–24 мин',tone:'Спина и разгрузка',category:'back',level:'Лёгкая',items:['catCow','birdDog','row','wallSlide','hinge','child']},
  POSTURE:{title:'Осанка и лопатки',duration:'16–22 мин',tone:'Осанка',category:'back',level:'Лёгкая',items:['chinTuck','wallSlide','row','chestStretch','birdDog','swan']},
  CARDIO:{title:'Кардио A · без прыжков',duration:'20–26 мин',tone:'Пульс без ударной нагрузки',category:'cardio',level:'Средняя',items:['march','stepTouch','boxing','crossCrunch','skater','squat']},
  INTERVAL:{title:'Кардио B · интервальная',duration:'16–20 мин',tone:'Интервалы без прыжков',category:'cardio',level:'Выше средней',items:['march','stepTouch','boxing','skater','crossCrunch','sumo']},
  MOBILITY:{title:'Мобилизация всего тела',duration:'10–15 мин',tone:'Подвижность',category:'recovery',level:'Очень лёгкая',items:['shoulderCircles','catCow','ankleWall','lowLunge','twist','hinge']},
  STRETCH:{title:'Растяжка всего тела',duration:'12–18 мин',tone:'Восстановление',category:'recovery',level:'Очень лёгкая',items:['calf','lowLunge','chestStretch','figure4','twist','child']},
  PELVIC:{title:'Тазовое дно · мягкая практика',duration:'12–16 мин',tone:'Контроль и дыхание',category:'pelvic',level:'Очень лёгкая',items:['pelvicBreath','pelvicLift','heelSlide','bridge','clam','child']}
};

const schedule=['STRETCH','STRENGTH','PILATES','BACK','LOWER','YOGA','CORE'];
const categoryOrder=['all','strength','core','pilates','yoga','back','cardio','recovery','pelvic'];
const categoryLabel={all:'Все',strength:'Силовые',core:'Пресс и кор',pilates:'Пилатес',yoga:'Йога',back:'Спина',cardio:'Кардио',recovery:'Восстановление',pelvic:'Тазовое дно'};
const sessionKey='my60-workout-session-v4';
let activeCategory='all',tick=null;

function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function todayKey(d){d=d||new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function currentType(){return schedule[new Date().getDay()]||'STRENGTH'}
function item(type,index){const p=W[type],k=p&&p.items[index],x=k&&E[k];return x?{...x,key:k}:null}
function done(type,d){try{return !!(window.S&&S.workouts&&Array.isArray(S.workouts[todayKey(d)])&&S.workouts[todayKey(d)].includes(type))}catch(e){return false}}
function saveState(){try{if(typeof window.save==='function')window.save()}catch(e){}}
function markDone(type){try{if(!window.S)return;const k=typeof window.key==='function'?window.key():todayKey();if(!S.workouts[k])S.workouts[k]=[];if(!S.workouts[k].includes(type))S.workouts[k].push(type);saveState()}catch(e){}}
function load(){try{return JSON.parse(localStorage.getItem(sessionKey)||'null')}catch(e){return null}}
function store(v){try{v?localStorage.setItem(sessionKey,JSON.stringify(v)):localStorage.removeItem(sessionKey)}catch(e){}}
function parseDose(text){const sets=(text.match(/^\s*(\d+)\s*[×x]/)||[])[1];let seconds=0;const sec=(text.match(/[×x]?\s*(\d+)\s*сек/)||[])[1];const min=(text.match(/(\d+)\s*мин/)||[])[1];if(sec)seconds=+sec;if(min)seconds=+min*60;return{sets:+sets||1,seconds}}
function totalSets(type){return W[type].items.reduce((s,_,i)=>s+parseDose(item(type,i).dose).sets,0)}
function completedSets(s){let c=0;for(let i=0;i<s.e;i++)c+=parseDose(item(s.type,i).dose).sets;return c+s.set}
function timerText(v){return Math.floor(v/60)+':'+String(v%60).padStart(2,'0')}

function injectStyle(){if(document.getElementById('my60TextWorkoutStyle'))return;const st=document.createElement('style');st.id='my60TextWorkoutStyle';st.textContent=`
.my60-v4{display:flex;flex-direction:column;gap:12px}.my60-week-strip{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.my60-week-strip .d{padding:8px 2px;border-radius:13px;background:#f3f3ef;text-align:center;font-size:9px;color:#8b908c}.my60-week-strip .d b{display:block;font-size:12px;color:#343a36;margin-top:3px}.my60-week-strip .d.today{background:#171d1a;color:#fff}.my60-week-strip .d.today b{color:#fff}.my60-week-strip .d.done{background:#e5f1e4;color:#4b7553}
.my60-today-card,.my60-library2{background:#fff;border:1px solid rgba(21,25,23,.07);border-radius:25px;padding:16px;box-shadow:0 10px 28px rgba(23,31,27,.05)}.my60-today-card .kicker,.my60-library-title span{font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:#929792;font-weight:850}.my60-today-card h3{font-size:24px;margin:6px 0 4px;letter-spacing:-.04em}.my60-today-card p{font-size:11px;color:#858b86;margin:0 0 12px;line-height:1.45}.my60-today-actions{display:grid;grid-template-columns:1.3fr .7fr;gap:8px}.my60-today-actions button,.my60-preview-start{border:0;border-radius:15px;padding:12px;font-weight:850}.my60-primary,.my60-preview-start{background:#171d1a;color:#fff}.my60-secondary{background:#efefeb;color:#5f6661}
.my60-library-title{display:flex;justify-content:space-between;align-items:end;margin-bottom:12px}.my60-library-title b{display:block;font-size:21px;margin-top:3px}.my60-library-title i{font-style:normal;color:#9a9e9a;font-size:11px}.my60-cat-scroll{display:flex;gap:6px;overflow:auto;padding-bottom:8px;scrollbar-width:none}.my60-cat-scroll::-webkit-scrollbar{display:none}.my60-cat-scroll button{white-space:nowrap;border:0;border-radius:999px;background:#f0f0ec;color:#6f756f;padding:9px 11px;font-size:10px;font-weight:800}.my60-cat-scroll button.active{background:#171d1a;color:#fff}.my60-grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px}.my60-card2{border:1px solid rgba(21,25,23,.07);background:#fafaf8;border-radius:19px;padding:12px;text-align:left;color:#222825;min-height:104px}.my60-card2 strong{display:block;font-size:13px;line-height:1.2}.my60-card2 span{display:block;color:#8a8f8c;font-size:9px;margin-top:6px;line-height:1.3}.my60-card2 small{display:block;margin-top:8px;color:#a85f68;font-size:9px;font-weight:850}.my60-card2.today{border-color:#c77a81;background:#fbf2f1}.my60-resume{border:0;border-radius:18px;padding:12px 14px;background:#f4e8e7;color:#7d4f55;text-align:left}.my60-resume b,.my60-resume span{display:block}.my60-resume span{font-size:10px;margin-top:3px}
.my60-preview,.my60-player{position:fixed;inset:0;z-index:10050;background:#f8f8f5;display:none;overflow:auto}.my60-preview.open,.my60-player.open{display:block}.my60-overlay-inner{width:min(760px,100%);margin:auto;padding:calc(14px + env(safe-area-inset-top)) 14px calc(24px + env(safe-area-inset-bottom))}.my60-overlay-top{display:grid;grid-template-columns:40px 1fr 40px;gap:8px;align-items:center;margin-bottom:12px}.my60-overlay-top button{border:0;width:40px;height:40px;border-radius:13px;background:#eaeae6;font-size:22px}.my60-overlay-top span,.my60-overlay-top b{display:block;text-align:center}.my60-overlay-top span{font-size:9px;color:#999e99;text-transform:uppercase;letter-spacing:.08em}.my60-overlay-top b{font-size:13px}.my60-preview-hero{background:#171d1a;color:#fff;border-radius:26px;padding:18px}.my60-preview-hero span{font-size:10px;color:#c8cbc8}.my60-preview-hero h2{font-size:27px;line-height:1.02;margin:7px 0}.my60-preview-hero p{font-size:11px;color:#c8cbc8}.my60-preview-start{width:100%;background:#fff;color:#171d1a;margin-top:8px}.my60-preview-list{display:flex;flex-direction:column;gap:8px;margin-top:10px}.my60-preview-item{background:#fff;border:1px solid rgba(21,25,23,.07);border-radius:18px;padding:13px}.my60-preview-item b{display:block;font-size:14px}.my60-preview-item .meta{font-size:9px;color:#a15f67;margin:4px 0 8px;font-weight:800}.my60-preview-item ol{margin:0;padding-left:19px;color:#656b66;font-size:10px;line-height:1.45}.my60-preview-item .tip{margin-top:8px;padding:8px 9px;background:#f4f1ed;border-radius:11px;font-size:9px;color:#756d67}
.my60-progress{height:6px;border-radius:99px;background:#e5e5e1;overflow:hidden;margin-bottom:12px}.my60-progress span{display:block;height:100%;background:#b96c75}.my60-player-card{background:#fff;border-radius:26px;padding:17px;border:1px solid rgba(21,25,23,.07)}.my60-player-copy>span{font-size:10px;color:#a45f67;font-weight:850;text-transform:uppercase;letter-spacing:.07em}.my60-player-copy h2{font-size:28px;line-height:1.02;margin:7px 0}.my60-dose{display:inline-block;background:#171d1a;color:#fff;border-radius:999px;padding:8px 11px;font-size:11px;font-weight:850}.my60-set-row{display:flex;justify-content:space-between;align-items:center;margin:12px 0;font-size:10px;color:#7d837e}.my60-set-dots{display:flex;gap:5px}.my60-set-dots i{width:9px;height:9px;border-radius:50%;background:#dededa}.my60-set-dots i.done{background:#8eb08f}.my60-set-dots i.now{background:#b96c75}.my60-how{margin-top:10px}.my60-how h4{margin:0 0 8px;font-size:13px}.my60-how ol{margin:0;padding-left:20px}.my60-how li{margin:7px 0;color:#555c57;font-size:12px;line-height:1.45}.my60-tip{margin-top:12px;padding:11px 12px;border-radius:14px;background:#f5f0ec;font-size:11px;line-height:1.4;color:#6f6660}.my60-feel{margin-top:8px;font-size:10px;color:#7d837e}.my60-timer{display:grid;place-items:center;width:130px;height:130px;border-radius:50%;margin:16px auto 0;background:conic-gradient(#b96c75 var(--p),#ecece8 0)}.my60-timer>div{display:grid;place-items:center;width:108px;height:108px;border-radius:50%;background:#fff}.my60-timer b{font-size:29px}.my60-timer small{font-size:9px;color:#8f948f}.my60-player-actions{position:sticky;bottom:0;display:grid;grid-template-columns:54px 1fr 54px;gap:8px;margin-top:12px;padding-top:8px;background:linear-gradient(transparent,#f8f8f5 35%)}.my60-player-actions button{border:0;border-radius:16px;padding:14px 8px;font-weight:850}.my60-player-actions .main{background:#171d1a;color:#fff}.my60-player-actions .back,.my60-player-actions .skip{background:#e9e9e5;color:#59605b;font-size:20px}.my60-rest-card,.my60-finish{background:#fff;border:1px solid rgba(21,25,23,.07);border-radius:26px;padding:20px;text-align:center}.my60-rest-card h2,.my60-finish h2{font-size:29px;margin:7px 0}.my60-rest-card p,.my60-finish p{font-size:11px;color:#808680}.my60-rest-next{margin-top:14px;padding:12px;background:#f3f3ef;border-radius:15px;text-align:left}.my60-rest-next span,.my60-rest-next b,.my60-rest-next small{display:block}.my60-rest-next span{font-size:8px;text-transform:uppercase;color:#9a9e99}.my60-rest-next b{font-size:13px;margin-top:2px}.my60-rest-next small{font-size:9px;color:#858a86;margin-top:2px}.my60-finish-mark{width:62px;height:62px;border-radius:50%;display:grid;place-items:center;margin:auto;background:#e3f0e2;color:#47764d;font-size:28px}.my60-finish button{border:0;border-radius:15px;padding:13px 18px;background:#171d1a;color:#fff;font-weight:850;width:100%;margin-top:10px}body.my60-workout-open{overflow:hidden}
@media(max-width:430px){.my60-grid2{grid-template-columns:1fr 1fr}.my60-card2{min-height:100px}.my60-player-copy h2{font-size:25px}.my60-overlay-inner{padding-left:11px;padding-right:11px}}
`;document.head.appendChild(st)}

function weekStrip(){const now=new Date(),off=(now.getDay()+6)%7,mon=new Date(now);mon.setDate(now.getDate()-off);const labels=['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС'];let out='<div class="my60-week-strip">';for(let i=0;i<7;i++){const d=new Date(mon);d.setDate(mon.getDate()+i);const t=schedule[d.getDay()]||'STRENGTH';const isToday=todayKey(d)===todayKey(now);out+='<div class="d '+(isToday?'today ':'')+(done(t,d)?'done':'')+'"><span>'+labels[i]+'</span><b>'+(done(t,d)?'✓':d.getDate())+'</b></div>'}return out+'</div>'}
function hubMarkup(){const type=currentType(),m=W[type],resume=load(),types=Object.keys(W).filter(t=>activeCategory==='all'||W[t].category===activeCategory);return '<div class="my60-v4">'+weekStrip()+(resume?'<button class="my60-resume" onclick="My60Library.resume()"><b>Продолжить тренировку</b><span>'+esc(W[resume.type]?.title||'Тренировка')+' · упражнение '+(resume.e+1)+'</span></button>':'')+'<section class="my60-today-card"><span class="kicker">Сегодня · '+esc(m.tone)+'</span><h3>'+esc(m.title)+'</h3><p>'+esc(m.duration)+' · '+m.items.length+' упражнений · '+esc(m.level)+'. Без GIF: каждое упражнение открывается с подробным текстом, техникой и подсказками.</p><div class="my60-today-actions"><button class="my60-primary" onclick="My60Library.start(\''+type+'\')">'+(done(type)?'Повторить тренировку':'▶ Начать тренировку')+'</button><button class="my60-secondary" onclick="My60Library.preview(\''+type+'\')">Посмотреть</button></div></section><section class="my60-library2"><div class="my60-library-title"><div><span>Библиотека</span><b>Разные тренировки по цели</b></div><i>'+Object.keys(W).length+' программ</i></div><div class="my60-cat-scroll">'+categoryOrder.map(c=>'<button class="'+(c===activeCategory?'active':'')+'" onclick="My60Library.filter(\''+c+'\')">'+categoryLabel[c]+'</button>').join('')+'</div><div class="my60-grid2">'+types.map(t=>'<button class="my60-card2 '+(t===type?'today':'')+'" onclick="My60Library.preview(\''+t+'\')"><strong>'+esc(W[t].title)+'</strong><span>'+esc(W[t].duration)+' · '+W[t].items.length+' упражнений</span><small>'+esc(W[t].tone)+'</small></button>').join('')+'</div>'+(activeCategory==='pelvic'?'<div style="margin-top:10px;padding:10px;border-radius:13px;background:#f5f0ec;color:#71665f;font-size:10px;line-height:1.45">Тазовое дно тренируем мягко: без натуживания и задержки дыхания. При боли, тяжести или выраженном давлении вниз практику лучше прекратить.</div>':'')+'</section></div>'}
function renderHub(){injectStyle();const studio=document.getElementById('workoutStudio');if(!studio)return false;studio.innerHTML=hubMarkup();studio.dataset.my60Library='4';return true}
function overlay(id,cls){let el=document.getElementById(id);if(!el){el=document.createElement('div');el.id=id;el.className=cls;document.body.appendChild(el)}return el}
function close(){document.querySelectorAll('.my60-preview,.my60-player').forEach(x=>x.classList.remove('open'));document.body.classList.remove('my60-workout-open');if(tick){clearInterval(tick);tick=null}}
function preview(type){if(!W[type])return;const m=W[type],root=overlay('my60WorkoutPreview','my60-preview');root.innerHTML='<div class="my60-overlay-inner"><div class="my60-overlay-top"><button onclick="My60Library.close()">×</button><div><span>'+esc(m.tone)+'</span><b>'+esc(m.title)+'</b></div><i></i></div><div class="my60-preview-hero"><span>'+esc(m.level)+'</span><h2>'+esc(m.title)+'</h2><p>'+esc(m.duration)+' · '+m.items.length+' упражнений</p><button class="my60-preview-start" onclick="My60Library.start(\''+type+'\')">▶ Начать</button></div><div class="my60-preview-list">'+m.items.map((_,i)=>{const r=item(type,i);return '<div class="my60-preview-item"><b>'+(i+1)+'. '+esc(r.name)+'</b><div class="meta">'+esc(r.focus)+' · '+esc(r.dose)+'</div><ol>'+r.steps.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol><div class="tip"><b>Важно:</b> '+esc(r.tip)+'</div></div>'}).join('')+'</div></div>';root.classList.add('open');document.body.classList.add('my60-workout-open')}
function newSession(type){const d=parseDose(item(type,0).dose);return{type,e:0,set:0,phase:'exercise',left:d.seconds||0,running:false,pending:null,started:Date.now()}}
function start(type){if(!W[type])return;store(newSession(type));renderPlayer(load())}
function resume(){const s=load();if(s&&W[s.type])renderPlayer(s);else renderHub()}
function startTick(){if(tick)clearInterval(tick);tick=setInterval(()=>{const s=load();if(!s||!s.running)return;if(s.left>0)s.left--;if(s.left<=0){s.running=false;store(s);if(s.phase==='rest')advance(s);else completeSet(s);return}store(s);const el=document.getElementById('my60Clock');if(el)el.textContent=timerText(Math.max(0,s.left))},1000)}
function renderPlayer(s){if(!s||!W[s.type])return;close();const root=overlay('my60WorkoutPlayer','my60-player');root.classList.add('open');document.body.classList.add('my60-workout-open');if(s.phase==='finish')return finishMarkup(root,s);if(s.phase==='rest')return restMarkup(root,s);const ex=item(s.type,s.e),d=parseDose(ex.dose),pct=Math.round(completedSets(s)/Math.max(1,totalSets(s.type))*100),dots=Array.from({length:d.sets},(_,i)=>'<i class="'+(i<s.set?'done':i===s.set?'now':'')+'"></i>').join('');root.innerHTML='<div class="my60-overlay-inner"><div class="my60-overlay-top"><button onclick="My60Library.close()">×</button><div><span>'+esc(W[s.type].title)+'</span><b>Упражнение '+(s.e+1)+' из '+W[s.type].items.length+'</b></div><button onclick="My60Library.preview(\''+s.type+'\')" style="font-size:16px">≡</button></div><div class="my60-progress"><span style="width:'+pct+'%"></span></div><div class="my60-player-card"><div class="my60-player-copy"><span>'+esc(ex.focus)+'</span><h2>'+esc(ex.name)+'</h2><div class="my60-dose">'+esc(ex.dose)+'</div><div class="my60-set-row"><div class="my60-set-dots">'+dots+'</div><span>Подход '+(s.set+1)+' из '+d.sets+'</span></div><div class="my60-how"><h4>Как делать</h4><ol>'+ex.steps.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ol></div><div class="my60-tip"><b>Важно:</b> '+esc(ex.tip)+'</div><div class="my60-feel"><b>Что должно работать:</b> '+esc(ex.feel)+'</div>'+(d.seconds?'<div class="my60-timer" style="--p:'+(d.seconds?s.left/d.seconds*100:0)+'%"><div><b id="my60Clock">'+timerText(s.left)+'</b><small>'+(s.running?'идёт время':'таймер')+'</small></div></div>':'')+'</div></div><div class="my60-player-actions"><button class="back" onclick="My60Library.back()">‹</button><button class="main" onclick="My60Library.primary()">'+(d.seconds?(s.running?'Пауза':'Старт '+timerText(d.seconds)):'Подход выполнен ✓')+'</button><button class="skip" onclick="My60Library.skip()">›</button></div></div>';store(s);if(s.running)startTick()}
function primary(){const s=load();if(!s)return;if(s.phase==='rest'){s.running=!s.running;store(s);renderPlayer(s);return}const d=parseDose(item(s.type,s.e).dose);if(d.seconds){s.running=!s.running;if(s.left<=0)s.left=d.seconds;store(s);renderPlayer(s)}else completeSet(s)}
function completeSet(s){const d=parseDose(item(s.type,s.e).dose);s.running=false;if(s.set+1<d.sets)s.pending={e:s.e,set:s.set+1};else if(s.e+1<W[s.type].items.length)s.pending={e:s.e+1,set:0};else{s.phase='finish';store(s);return renderPlayer(s)}s.phase='rest';s.left=25;s.running=true;store(s);renderPlayer(s)}
function advance(s){const p=s.pending||{e:Math.min(s.e+1,W[s.type].items.length-1),set:0};s.e=p.e;s.set=p.set;s.pending=null;s.phase='exercise';const d=parseDose(item(s.type,s.e).dose);s.left=d.seconds||0;s.running=false;store(s);renderPlayer(s)}
function skip(){const s=load();if(!s)return;if(s.phase==='rest')return advance(s);if(s.e+1>=W[s.type].items.length){s.phase='finish';store(s);return renderPlayer(s)}s.e++;s.set=0;const d=parseDose(item(s.type,s.e).dose);s.left=d.seconds||0;s.running=false;store(s);renderPlayer(s)}
function back(){const s=load();if(!s)return;if(s.phase==='rest'){s.phase='exercise';s.pending=null}else if(s.set>0)s.set--;else if(s.e>0){s.e--;s.set=Math.max(0,parseDose(item(s.type,s.e).dose).sets-1)}const d=parseDose(item(s.type,s.e).dose);s.left=d.seconds||0;s.running=false;store(s);renderPlayer(s)}
function restMarkup(root,s){const p=s.pending||{e:Math.min(s.e+1,W[s.type].items.length-1),set:0},next=item(s.type,p.e);root.innerHTML='<div class="my60-overlay-inner"><div class="my60-overlay-top"><button onclick="My60Library.close()">×</button><div><span>Отдых</span><b>'+esc(W[s.type].title)+'</b></div><i></i></div><div class="my60-rest-card"><span style="font-size:10px;color:#999">Восстанови дыхание</span><h2>Отдых</h2><p>Следующий подход начнётся автоматически</p><div class="my60-timer" style="--p:'+(s.left/25*100)+'%"><div><b id="my60Clock">'+timerText(s.left)+'</b><small>отдых</small></div></div><div class="my60-rest-next"><span>Дальше</span><b>'+esc(next.name)+'</b><small>'+esc(next.dose)+' · '+esc(next.focus)+'</small></div><div class="my60-player-actions"><button onclick="My60Library.moreRest()">+15</button><button class="main" onclick="My60Library.skipRest()">Пропустить отдых</button><button onclick="My60Library.primary()">'+(s.running?'Ⅱ':'▶')+'</button></div></div></div>';store(s);if(s.running)startTick()}
function moreRest(){const s=load();if(!s||s.phase!=='rest')return;s.left+=15;store(s);renderPlayer(s)}
function skipRest(){const s=load();if(s&&s.phase==='rest')advance(s)}
function finishMarkup(root,s){markDone(s.type);store(null);root.innerHTML='<div class="my60-overlay-inner"><div class="my60-finish"><div class="my60-finish-mark">✓</div><h2>Тренировка готова</h2><p>'+esc(W[s.type].title)+' · '+W[s.type].items.length+' упражнений. На сегодня достаточно.</p><button onclick="My60Library.finish()">Готово</button></div></div>';renderHub()}
function finish(){close();renderHub()}
function filter(c){activeCategory=categoryOrder.includes(c)?c:'all';renderHub()}
window.My60Library={start,resume,preview,close,primary,skip,back,moreRest,skipRest,finish,filter,programs:W};
function boot(){injectStyle();let tries=0;const iv=setInterval(()=>{tries++;if(renderHub()||tries>40)clearInterval(iv)},150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
