(function(){
'use strict';

const SESSION='my60-variety-session-v1';
let activeCat='all',patched=false,observerTimer=null;

const X={
  marchCore:{n:'Марш с активным кором',f:'Пресс · координация',d:'3 × 40 сек',s:['Встань ровно, стопы под тазом, плечи расслабь.','На выдохе подними одно колено и мягко подтяни низ живота.','Опусти ногу без удара и чередуй стороны в спокойном темпе.'],t:'Не отклоняй корпус назад ради высокого колена.',feel:'Низ живота и работу корпуса.'},
  kneeElbow:{n:'Колено к противоположному локтю',f:'Косые мышцы живота',d:'3 × 12 / сторону',s:['Встань устойчиво, руки у висков, локти раскрыты.','Подними правое колено и слегка поверни грудную клетку к нему.','Вернись в центр и повтори на другую сторону.'],t:'Не тяни голову руками и не делай резких скручиваний.',feel:'Боковые мышцы живота.'},
  deadbugHeel:{n:'Dead bug — пятка вниз',f:'Глубокий кор',d:'3 × 10 / сторону',s:['Ляг на спину, колени над тазом под углом около 90°.','На выдохе мягко прижми поясницу и опусти одну пятку к полу.','Верни ногу и повтори другой ногой, сохраняя живот собранным.'],t:'Если поясница отрывается, опускай пятку не так низко.',feel:'Глубокий низ живота.'},
  reverseCrunch:{n:'Обратное подкручивание таза',f:'Низ живота',d:'3 × 10',s:['Ляг на спину, колени согнуты над тазом.','На выдохе подтяни колени чуть к груди и слегка приподними таз.','Медленно верни таз на коврик без маха ногами.'],t:'Движение маленькое; не раскачивайся.',feel:'Нижнюю часть пресса.'},
  heelTap:{n:'Касание пяток лёжа',f:'Талия · косые мышцы',d:'3 × 14 / сторону',s:['Ляг на спину, стопы близко к ягодицам, лопатки слегка приподними.','Потянись правой рукой к правой пятке.','Вернись через центр и потянись к левой пятке.'],t:'Шею держи длинной, не прижимай подбородок к груди.',feel:'Бока живота.'},
  sideKnee:{n:'Боковое подтягивание колена лёжа',f:'Талия · нижний пресс',d:'3 × 10 / сторону',s:['Ляг на бок, опираясь головой на нижнюю руку.','Подтяни верхнее колено к корпусу, слегка сокращая бок живота.','Медленно вытяни ногу обратно и повтори.'],t:'Не перекатывай таз назад.',feel:'Бок живота и нижнюю часть пресса.'},
  plankKnees:{n:'Планка с колен',f:'Кор · плечи',d:'3 × 25 сек',s:['Встань на предплечья и колени, локти под плечами.','Подтяни живот и выстрой линию от макушки до колен.','Дыши спокойно и удерживай положение без провисания.'],t:'Если поясница устает, сократи время.',feel:'Весь кор.'},
  bearHold:{n:'Стол на четвереньках — отрыв колен',f:'Глубокий кор',d:'3 × 20 сек',s:['Встань на четвереньки: ладони под плечами, колени под тазом.','Подтяни живот и приподними колени на 2–3 см над полом.','Удерживай спину ровной, затем мягко опусти колени.'],t:'Не округляй и не прогибай поясницу.',feel:'Глубокое напряжение живота.'},
  hundredPrep:{n:'Пилатес Hundred — подготовка',f:'Пилатес · кор',d:'3 × 30 сек',s:['Ляг на спину, колени согнуты, стопы на полу.','Приподними голову и лопатки, руки вытяни вдоль тела.','Делай короткие движения руками вверх-вниз, сохраняя ровное дыхание.'],t:'Если шея устает, оставь голову на полу.',feel:'Пресс и дыхательный контроль.'},
  pilatesToeTap:{n:'Пилатес toe taps',f:'Пилатес · низ живота',d:'3 × 10 / сторону',s:['Ляг на спину, ноги подними в положение «стол».','На выдохе опусти носок одной ноги к полу.','Верни ногу и поменяй сторону, не меняя положение таза.'],t:'Поясница не должна сильно прогибаться.',feel:'Глубокий низ живота.'},
  pilatesLegCircle:{n:'Круги ногой лёжа',f:'Пилатес · таз · бедро',d:'2 × 8 / сторону',s:['Ляг на спину, одну ногу согни, вторую вытяни вверх насколько комфортно.','Нарисуй прямой ногой небольшой круг из тазобедренного сустава.','Сохраняй таз неподвижным и после круга поменяй направление.'],t:'Круг меньше — контроль лучше.',feel:'Кор и мышцы вокруг тазобедренного сустава.'},
  pilatesSingleLeg:{n:'Пилатес single leg stretch',f:'Пилатес · пресс',d:'3 × 8 / сторону',s:['Ляг на спину и подтяни одно колено к груди.','Вторую ногу вытяни вперёд под удобным углом.','Плавно поменяй ноги, удерживая живот собранным.'],t:'Можно держать голову на полу.',feel:'Пресс и контроль таза.'},
  pilatesBridge:{n:'Пилатес-мост по позвонкам',f:'Пилатес · ягодицы · спина',d:'3 × 10',s:['Ляг на спину, стопы на ширине таза.','На выдохе подкрути таз и поднимай позвоночник постепенно, снизу вверх.','Так же медленно опусти спину, укладывая позвонок за позвонком.'],t:'Не поднимайся слишком высоко.',feel:'Ягодицы, заднюю поверхность тела и мягкую работу спины.'},
  pilatesSideKick:{n:'Пилатес side kick',f:'Пилатес · ягодицы · бедро',d:'2 × 10 / сторону',s:['Ляг на бок, корпус вытянут в одну линию.','Подними верхнюю ногу до уровня таза и выведи её немного вперёд.','Верни ногу назад без раскачки корпуса.'],t:'Амплитуда меньше, если таз начинает двигаться.',feel:'Бок ягодицы и бедро.'},
  pilatesSwimming:{n:'Пилатес swimming — лёгкий',f:'Пилатес · спина · ягодицы',d:'3 × 20 сек',s:['Ляг на живот, руки вытяни вперёд или оставь у висков.','Слегка приподними противоположные руку и ногу.','Чередуй стороны медленно, сохраняя шею длинной.'],t:'Не стремись поднять конечности высоко.',feel:'Спину и ягодицы, не поясницу.'},
  bridgeMarch:{n:'Марш в ягодичном мосту',f:'Ягодицы · кор',d:'3 × 8 / ногу',s:['Подними таз в обычный ягодичный мост.','Не меняя высоту таза, слегка оторви одну стопу от пола.','Поставь её обратно и поменяй сторону.'],t:'Если таз качается, вернись к обычному мосту.',feel:'Ягодицы и кор.'},
  frogPump:{n:'Frog pumps',f:'Ягодицы',d:'3 × 20',s:['Ляг на спину, соедини стопы подошвами и разведи колени комфортно.','На выдохе подними таз, сохраняя рёбра спокойными.','Сожми ягодицы и плавно опусти таз.'],t:'Амплитуда может быть небольшой.',feel:'Ягодицы.'},
  donkeyKick:{n:'Отведение согнутой ноги на четвереньках',f:'Ягодицы',d:'3 × 12 / ногу',s:['Встань на четвереньки и подтяни живот.','Сохраняя колено согнутым, подними стопу вверх до момента, пока таз остаётся ровным.','Опусти колено почти до пола и повтори.'],t:'Не прогибай поясницу ради высоты ноги.',feel:'Большую ягодичную мышцу.'},
  fireHydrant:{n:'Отведение колена в сторону',f:'Средняя ягодичная',d:'3 × 12 / сторону',s:['Встань на четвереньки, ладони под плечами.','Не разворачивая таз, подними согнутое колено в сторону.','Медленно верни колено вниз.'],t:'Корпус не заваливай на опорную сторону.',feel:'Бок ягодицы.'},
  sideSquat:{n:'Боковой присед с переносом веса',f:'Ягодицы · ноги',d:'3 × 10 / сторону',s:['Поставь стопы шире плеч.','Перенеси вес вправо, уводя таз назад и сгибая правую ногу.','Вернись в центр и повтори влево.'],t:'Колено согнутой ноги направляй по носку.',feel:'Ягодицы и внутреннюю поверхность бёдер.'},
  wallSit:{n:'Статический стул у стены',f:'Бёдра · ягодицы',d:'3 × 30 сек',s:['Прижмись спиной к стене, стопы поставь немного впереди.','Скользи вниз до комфортной глубины.','Удерживай положение, колени направляй вперёд по линии стоп.'],t:'Не нужно садиться до угла 90°.',feel:'Переднюю поверхность бёдер.'},
  hipHinge:{n:'Наклон-таз назад без веса',f:'Ягодицы · задняя поверхность бедра',d:'3 × 12',s:['Встань ровно, ладони положи на таз.','Слегка согни колени и отведи таз назад, сохраняя спину длинной.','Нажми стопами в пол и верни таз вперёд.'],t:'Не округляй спину.',feel:'Заднюю поверхность бёдер.'},
  wallSlide:{n:'Скольжение руками по стене',f:'Осанка · лопатки',d:'3 × 10',s:['Встань спиной к стене, рёбра держи собранными.','Согни локти и мягко прижми руки к стене насколько получается.','Скользи руками вверх и вниз, не поднимая плечи.'],t:'Не прогибай поясницу ради контакта со стеной.',feel:'Мышцы между лопатками.'},
  chinTuck:{n:'Подбородок назад',f:'Шея · осанка',d:'3 × 10',s:['Сядь или встань ровно, взгляд направь вперёд.','Не наклоняя голову, мягко сдвинь подбородок назад.','Задержись на 2 секунды и отпусти.'],t:'Движение маленькое и без давления.',feel:'Глубокие мышцы шеи.'},
  reverseFly:{n:'Обратные разведения рук',f:'Верх спины · лопатки',d:'3 × 12',s:['Слегка наклони корпус вперёд с длинной спиной.','Руки опусти вниз, локти слегка согни.','Разведи руки в стороны, сближая лопатки, затем медленно опусти.'],t:'Вес должен быть очень лёгким.',feel:'Верх спины.'},
  wallAngel:{n:'Ангел у стены',f:'Осанка · плечи',d:'2 × 8',s:['Встань спиной к стене и согни локти под 90°.','Сохраняй рёбра собранными и плечи опущенными.','Плавно скользи локтями и кистями вверх, затем вниз.'],t:'Работай только в безболезненной амплитуде.',feel:'Лопатки и раскрытие плеч.'},
  catCow:{n:'Кошка-корова',f:'Спина · мобильность',d:'2 × 8',s:['Встань на четвереньки.','На выдохе мягко округли спину и опусти голову.','На вдохе раскрой грудную клетку и слегка прогнись без залома в пояснице.'],t:'Двигайся медленно вместе с дыханием.',feel:'Мягкую подвижность всей спины.'},
  threadNeedle:{n:'Нить в иголку',f:'Грудной отдел · плечо',d:'2 × 8 / сторону',s:['Встань на четвереньки.','Проведи правую руку под левой и мягко поверни грудную клетку.','Вернись и раскрой правую руку вверх, затем поменяй сторону.'],t:'Таз оставляй примерно над коленями.',feel:'Грудной отдел и заднюю поверхность плеча.'},
  childPose:{n:'Поза ребёнка',f:'Спина · дыхание',d:'45 сек',s:['Опусти таз к пяткам насколько комфортно.','Вытяни руки вперёд или положи вдоль тела.','Расслабь шею и сделай несколько медленных выдохов.'],t:'Если коленям неудобно, положи подушку под таз.',feel:'Мягкое вытяжение спины.'},
  lowLunge:{n:'Низкий выпад',f:'Йога · таз · бёдра',d:'40 сек / сторону',s:['Из положения на четвереньках поставь одну стопу между ладонями.','Заднее колено оставь на полу и вырасти корпусом вверх.','Мягко направь таз вперёд, не прогибаясь в пояснице.'],t:'Подложи полотенце под колено, если нужно.',feel:'Переднюю поверхность бедра и область таза.'},
  dog:{n:'Собака мордой вниз',f:'Йога · спина · ноги',d:'40 сек',s:['Поставь ладони на пол и подними таз вверх и назад.','Колени можно заметно согнуть, чтобы удлинить спину.','Отталкивай пол ладонями и направляй грудную клетку к бёдрам.'],t:'Прямые ноги не являются целью.',feel:'Спину и заднюю поверхность ног.'},
  supineTwist:{n:'Скрутка лёжа',f:'Йога · спина · бока',d:'40 сек / сторону',s:['Ляг на спину и подтяни колени к груди.','Опусти колени в одну сторону, руки раскрой в стороны.','Оставь плечи тяжёлыми на полу и спокойно дыши.'],t:'Не дави колени к полу рукой.',feel:'Бок корпуса и спину.'},
  butterfly:{n:'Бабочка сидя',f:'Йога · таз · внутренняя поверхность бедра',d:'45 сек',s:['Сядь и соедини стопы подошвами.','Выпрями спину и позволь коленям опуститься в стороны.','Можно слегка наклониться вперёд от тазобедренных суставов.'],t:'Не дави руками на колени.',feel:'Внутреннюю поверхность бёдер.'},
  figure4:{n:'Фигура 4 лёжа',f:'Йога · ягодицы · таз',d:'45 сек / сторону',s:['Ляг на спину и положи правую лодыжку на левое бедро.','Подтяни левую ногу к себе, держась за бедро.','Сохраняй крестец на полу и спокойно дыши.'],t:'Колено верхней ноги не прижимай силой.',feel:'Ягодицу и наружную поверхность бедра.'},
  kneesChest:{n:'Колени к груди',f:'Йога · поясница',d:'45 сек',s:['Ляг на спину и подтяни колени к груди.','Обхвати голени или заднюю поверхность бёдер.','Слегка покачайся или оставайся неподвижно и дыши.'],t:'Плечи и челюсть расслабь.',feel:'Расслабление поясницы.'},
  breath4:{n:'Дыхание 4–6',f:'Йога · расслабление',d:'2 мин',s:['Ляг или сядь удобно и расслабь плечи.','Спокойно вдохни примерно на 4 счёта.','Выдыхай немного длиннее — примерно на 6 счётов, без усилия.'],t:'Если длинный выдох неприятен, дыши естественно.',feel:'Постепенное снижение напряжения.'},
  walkMarch:{n:'Активный марш',f:'Кардио без прыжков',d:'4 × 45 сек',s:['Встань ровно и начни активно маршировать на месте.','Двигай руками в противоход ногам.','Сохраняй темп, при котором дыхание ускоряется, но остаётся контролируемым.'],t:'Не топай и не задирай колени через силу.',feel:'Работу всего тела и умеренное учащение пульса.'},
  boxer:{n:'Бокс стоя',f:'Кардио · руки · кор',d:'4 × 40 сек',s:['Поставь одну ногу чуть впереди, колени мягкие.','Поочерёдно выпрямляй руки вперёд, слегка поворачивая корпус.','Возвращай кулак к лицу после каждого удара.'],t:'Не блокируй локти в конце удара.',feel:'Плечи, руки, кор и повышение пульса.'},
  sideStep:{n:'Шаги в сторону с руками',f:'Кардио · ноги',d:'4 × 45 сек',s:['Слегка согни колени.','Сделай шаг вправо и приставь левую ногу, затем влево.','Добавь свободные движения руками вверх или вперёд.'],t:'Шагай мягко и держи колени по направлению стоп.',feel:'Ноги и умеренную кардионагрузку.'},
  skaterStep:{n:'Конькобежец без прыжка',f:'Кардио · ягодицы',d:'4 × 40 сек',s:['Перенеси вес на правую ногу и шагни левой назад по диагонали.','Вернись через центр и сделай то же в другую сторону.','Двигай руками естественно и сохраняй мягкие колени.'],t:'Прыгать не нужно.',feel:'Ягодицы, ноги и пульс.'}
};

const S={
  ABS_EXPRESS:{title:'Пресс · 12 минут',cat:'abs',sub:'быстрая тренировка живота',level:'Средняя',items:['marchCore','deadbugHeel','reverseCrunch','heelTap','plankKnees']},
  ABS_LOWER_2:{title:'Низ живота · медленно',cat:'abs',sub:'контроль без рывков',level:'Средняя',items:['deadbugHeel','pilatesToeTap','reverseCrunch','bearHold','marchCore']},
  ABS_WAIST_2:{title:'Талия и косые',cat:'abs',sub:'боковая линия корпуса',level:'Средняя',items:['heelTap','kneeElbow','sideKnee','plankKnees','marchCore']},
  ABS_DEEP_2:{title:'Глубокий кор',cat:'abs',sub:'стабилизация живота',level:'Лёгкая',items:['deadbugHeel','pilatesToeTap','bearHold','plankKnees','marchCore']},
  ABS_STANDING:{title:'Пресс стоя',cat:'abs',sub:'без упражнений лёжа',level:'Лёгкая',items:['marchCore','kneeElbow','sideStep','skaterStep','marchCore']},
  ABS_SLOW:{title:'Пресс · спокойный темп',cat:'abs',sub:'техника и контроль',level:'Лёгкая',items:['deadbugHeel','heelTap','reverseCrunch','plankKnees','breath4']},

  PILATES_MORNING:{title:'Пилатес утром',cat:'pilates',sub:'мягко разбудить тело',level:'Лёгкая',items:['pilatesBridge','pilatesToeTap','pilatesLegCircle','pilatesSideKick','catCow']},
  PILATES_CORE_2:{title:'Пилатес · сильный кор',cat:'pilates',sub:'живот и контроль таза',level:'Средняя',items:['hundredPrep','pilatesToeTap','pilatesSingleLeg','pilatesBridge','deadbugHeel']},
  PILATES_LOWER_2:{title:'Пилатес · ноги и ягодицы',cat:'pilates',sub:'низ тела без прыжков',level:'Средняя',items:['pilatesBridge','pilatesSideKick','pilatesLegCircle','sideSquat','fireHydrant']},
  PILATES_POSTURE_2:{title:'Пилатес · осанка',cat:'pilates',sub:'спина и лопатки',level:'Лёгкая',items:['catCow','pilatesSwimming','wallSlide','chinTuck','childPose']},
  PILATES_STANDING:{title:'Пилатес стоя',cat:'pilates',sub:'баланс и тонус',level:'Средняя',items:['hipHinge','sideSquat','marchCore','wallSlide','calfHold']},
  PILATES_RELAX:{title:'Пилатес · восстановление',cat:'pilates',sub:'медленная практика',level:'Очень лёгкая',items:['catCow','pilatesBridge','pilatesLegCircle','childPose','breath4']},

  GLUTES_BRIDGE:{title:'Ягодицы · мосты',cat:'glutes',sub:'акцент на большую ягодичную',level:'Средняя',items:['pilatesBridge','bridgeMarch','frogPump','donkeyKick','hipHinge']},
  GLUTES_SIDE:{title:'Ягодицы · боковой акцент',cat:'glutes',sub:'средняя ягодичная',level:'Средняя',items:['fireHydrant','pilatesSideKick','sideSquat','skaterStep','figure4']},
  GLUTES_CONTROL:{title:'Ягодицы · медленно',cat:'glutes',sub:'без прыжков и спешки',level:'Лёгкая',items:['hipHinge','donkeyKick','fireHydrant','pilatesBridge','figure4']},
  LEGS_SCULPT:{title:'Ноги + ягодицы',cat:'glutes',sub:'бёдра и ягодицы',level:'Средняя',items:['sideSquat','wallSit','hipHinge','skaterStep','pilatesBridge']},
  LOWER_BALANCE:{title:'Низ тела · баланс',cat:'glutes',sub:'устойчивость и контроль',level:'Средняя',items:['sideSquat','marchCore','hipHinge','wallSit','figure4']},

  POSTURE_DESK:{title:'Осанка после рабочего дня',cat:'back',sub:'шея, грудной отдел, лопатки',level:'Лёгкая',items:['chinTuck','wallSlide','wallAngel','threadNeedle','childPose']},
  POSTURE_UPPER:{title:'Верх спины и лопатки',cat:'back',sub:'осанка и плечи',level:'Средняя',items:['reverseFly','wallSlide','wallAngel','chinTuck','threadNeedle']},
  BACK_MOBILITY:{title:'Мобильная спина',cat:'back',sub:'мягкое движение позвоночника',level:'Очень лёгкая',items:['catCow','threadNeedle','childPose','supineTwist','kneesChest']},

  YOGA_EVENING_2:{title:'Йога перед сном',cat:'yoga',sub:'мягко замедлиться',level:'Очень лёгкая',items:['childPose','butterfly','figure4','supineTwist','breath4']},
  YOGA_HIPS_2:{title:'Йога · раскрытие таза',cat:'yoga',sub:'бёдра и ягодицы',level:'Лёгкая',items:['lowLunge','butterfly','figure4','dog','childPose']},
  YOGA_BACK_2:{title:'Йога · спина и плечи',cat:'yoga',sub:'после сидячего дня',level:'Лёгкая',items:['catCow','threadNeedle','dog','supineTwist','childPose']},
  YOGA_STRETCH:{title:'Йога · растяжка всего тела',cat:'yoga',sub:'мягкая гибкость',level:'Лёгкая',items:['dog','lowLunge','butterfly','figure4','supineTwist']},
  YOGA_SLEEP:{title:'Йога · 10 минут сна',cat:'yoga',sub:'очень спокойная практика',level:'Очень лёгкая',items:['kneesChest','figure4','supineTwist','childPose','breath4']},

  CARDIO_WALK:{title:'Кардио · шаги дома',cat:'cardio',sub:'без прыжков',level:'Средняя',items:['walkMarch','sideStep','marchCore','skaterStep','walkMarch']},
  CARDIO_BOX:{title:'Кардио-бокс',cat:'cardio',sub:'руки, кор и пульс',level:'Средняя',items:['boxer','sideStep','kneeElbow','boxer','walkMarch']}
};

/* fallback for one standing pilates exercise */
X.calfHold={n:'Подъём на носки с балансом',f:'Икры · баланс',d:'3 × 12',s:['Встань ровно рядом с опорой.','Поднимись на носки и задержись на секунду.','Медленно опусти пятки и повтори.'],t:'Не заваливай стопы наружу.',feel:'Икры и мышцы стоп.'};

const cats={all:'Все новые',abs:'Пресс',pilates:'Пилатес',glutes:'Ягодицы и ноги',back:'Спина и осанка',yoga:'Йога',cardio:'Кардио'};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function read(){try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch(e){return null}}
function write(v){try{v?localStorage.setItem(SESSION,JSON.stringify(v)):localStorage.removeItem(SESSION)}catch(e){}}
function duration(p){let min=0;for(const id of p.items){const d=X[id].d,m=d.match(/(\d+)\s*сек/);min+=m?Math.max(1,Math.round(+m[1]/60)):2.5}return Math.max(8,Math.round(min))+'–'+Math.max(12,Math.round(min+5))+' мин'}
function markDone(type){try{if(!window.S)return;const k=typeof window.key==='function'?window.key():new Date().toISOString().slice(0,10);if(!S.workouts)S.workouts={};if(!S.workouts[k])S.workouts[k]=[];if(S.workouts[k].indexOf(type)<0)S.workouts[k].push(type);if(typeof window.save==='function')window.save()}catch(e){}}

function style(){if(document.getElementById('my60VarietyStyle'))return;const st=document.createElement('style');st.id='my60VarietyStyle';st.textContent=`
.my60-variety{margin-top:12px;background:#fff;border:1px solid rgba(21,25,23,.06);border-radius:25px;padding:16px;box-shadow:0 10px 28px rgba(23,31,27,.05)}.my60-variety-head{display:flex;justify-content:space-between;gap:10px;align-items:end}.my60-variety-head span{display:block;font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:#929792;font-weight:850}.my60-variety-head b{display:block;font-size:20px;margin-top:3px}.my60-variety-head small{font-size:10px;color:#969b97;text-align:right}.my60-variety-cats{display:flex;gap:6px;overflow:auto;padding:12px 0 10px;scrollbar-width:none}.my60-variety-cats::-webkit-scrollbar{display:none}.my60-variety-cats button{white-space:nowrap;border:0;border-radius:999px;background:#f1f1ee;color:#767c77;padding:9px 11px;font-size:10px;font-weight:850}.my60-variety-cats button.active{background:#171d1a;color:#fff}.my60-variety-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.my60-variety-card{border:1px solid rgba(21,25,23,.07);background:#fafaf8;border-radius:18px;padding:12px;text-align:left;color:#222825;min-height:104px}.my60-variety-card b{display:block;font-size:13px;line-height:1.18}.my60-variety-card span{display:block;font-size:9px;color:#8b918d;margin-top:5px;line-height:1.3}.my60-variety-card small{display:block;font-size:9px;color:#b0646c;font-weight:850;margin-top:8px}.my60-variety-resume{width:100%;border:0;border-radius:16px;background:#171d1a;color:#fff;padding:12px;text-align:left;margin:10px 0}.my60-variety-resume b,.my60-variety-resume span{display:block}.my60-variety-resume span{font-size:9px;opacity:.72;margin-top:3px}
.my60-vsheet{position:fixed;inset:0;z-index:10075;background:rgba(12,16,14,.5);backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);display:flex;align-items:flex-end}.my60-vsheet[hidden]{display:none!important}.my60-vinner{width:100%;max-width:760px;margin:auto;background:#fafaf8;border-radius:30px 30px 0 0;max-height:93vh;overflow:auto;padding:18px 14px calc(22px + env(safe-area-inset-bottom))}.my60-vtop{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.my60-vtop span{font-size:9px;text-transform:uppercase;letter-spacing:.1em;color:#9a9f9b;font-weight:850}.my60-vtop h3{font-size:23px;margin:4px 0 3px}.my60-vtop p{margin:0;color:#8b918d;font-size:10px}.my60-vclose{border:0;width:36px;height:36px;border-radius:12px;background:#ecece8;font-size:20px}.my60-vstart{width:100%;border:0;border-radius:15px;background:#171d1a;color:#fff;padding:12px;font-weight:850;margin:13px 0}.my60-vlist{display:flex;flex-direction:column;gap:7px}.my60-vitem{background:#fff;border:1px solid rgba(21,25,23,.07);border-radius:16px;padding:11px}.my60-vitem b{font-size:12px}.my60-vitem span{display:block;font-size:9px;color:#8d928e;margin-top:3px}.my60-vitem small{display:block;font-size:9px;color:#b0646c;margin-top:5px;font-weight:800}
.my60-vplayer{position:fixed;inset:0;z-index:10080;background:#f7f6f3;overflow:auto}.my60-vplayer[hidden]{display:none!important}.my60-vpinner{width:min(760px,100%);margin:auto;padding:calc(14px + env(safe-area-inset-top)) 14px calc(24px + env(safe-area-inset-bottom))}.my60-vphead{display:flex;justify-content:space-between;gap:12px;align-items:center}.my60-vphead button{border:0;width:38px;height:38px;border-radius:13px;background:#fff;font-size:19px}.my60-vphead span{display:block;font-size:9px;color:#999f9a;text-transform:uppercase;letter-spacing:.08em}.my60-vphead b{font-size:12px}.my60-vprogress{height:6px;background:#e6e5e1;border-radius:99px;margin:14px 0;overflow:hidden}.my60-vprogress i{display:block;height:100%;background:#b96d75}.my60-vexercise{background:#fff;border:1px solid rgba(21,25,23,.06);border-radius:26px;padding:18px;box-shadow:0 12px 32px rgba(23,31,27,.05)}.my60-vexercise>span{font-size:10px;color:#b0646c;font-weight:850}.my60-vexercise h2{font-size:28px;line-height:1.04;margin:7px 0}.my60-vdose{font-size:15px;font-weight:900;background:#f1efeb;border-radius:13px;padding:10px 12px;display:inline-block}.my60-vsteps{margin-top:16px;display:flex;flex-direction:column;gap:10px}.my60-vstep{display:grid;grid-template-columns:28px 1fr;gap:9px;align-items:start}.my60-vstep i{display:grid;place-items:center;width:28px;height:28px;border-radius:9px;background:#171d1a;color:#fff;font-style:normal;font-size:11px;font-weight:900}.my60-vstep p{margin:2px 0 0;font-size:12px;line-height:1.5;color:#4f5651}.my60-vtip,.my60-vfeel{margin-top:12px;border-radius:14px;padding:11px 12px;font-size:11px;line-height:1.45}.my60-vtip{background:#f8ecea;color:#76585a}.my60-vfeel{background:#edf4ed;color:#526952}.my60-vactions{display:grid;grid-template-columns:.7fr 1.6fr .7fr;gap:8px;margin-top:12px}.my60-vactions button{border:0;border-radius:15px;padding:13px 7px;font-weight:850}.my60-vactions .main{background:#171d1a;color:#fff}.my60-vfinish{text-align:center;padding:50px 15px}.my60-vfinish i{display:grid;place-items:center;width:68px;height:68px;border-radius:50%;background:#e5f1e5;color:#347246;font-style:normal;font-size:28px;margin:auto}.my60-vfinish h2{font-size:28px;margin:14px 0 6px}.my60-vfinish p{font-size:11px;color:#838984}.my60-vfinish button{border:0;border-radius:15px;background:#171d1a;color:#fff;padding:13px 28px;font-weight:850;margin-top:10px}
@media(max-width:430px){.my60-variety{padding:14px}.my60-variety-grid{gap:7px}.my60-variety-card{padding:11px;min-height:101px}.my60-vexercise h2{font-size:25px}}
`;document.head.appendChild(st)}

function panelMarkup(){const ids=Object.keys(S).filter(id=>activeCat==='all'||S[id].cat===activeCat),r=read();return '<section id="my60Variety" class="my60-variety"><div class="my60-variety-head"><div><span>Ещё больше вариантов</span><b>Разные тренировки</b></div><small>'+Object.keys(S).length+' дополнительных</small></div>'+(r&&S[r.type]?'<button class="my60-variety-resume" onclick="My60Variety.resume()"><b>Продолжить · '+esc(S[r.type].title)+'</b><span>Упражнение '+(r.e+1)+' из '+S[r.type].items.length+'</span></button>':'')+'<div class="my60-variety-cats">'+Object.entries(cats).map(([id,n])=>'<button class="'+(activeCat===id?'active':'')+'" onclick="My60Variety.filter(\''+id+'\')">'+n+'</button>').join('')+'</div><div class="my60-variety-grid">'+ids.map(id=>{const p=S[id];return '<button class="my60-variety-card" onclick="My60Variety.preview(\''+id+'\')"><b>'+esc(p.title)+'</b><span>'+esc(p.sub)+' · '+p.items.length+' упражнений</span><small>'+duration(p)+' · '+esc(p.level)+'</small></button>'}).join('')+'</div></section>'}
function ensurePanel(){const studio=document.getElementById('workoutStudio');if(!studio||!studio.querySelector('.my60-library2'))return false;if(document.getElementById('my60Variety'))return true;studio.querySelector('.my60-library2').insertAdjacentHTML('afterend',panelMarkup());return true}
function rerenderPanel(){const p=document.getElementById('my60Variety');if(p)p.outerHTML=panelMarkup();else ensurePanel()}
function overlay(id,cls){let el=document.getElementById(id);if(!el){el=document.createElement('div');el.id=id;el.className=cls;el.hidden=true;document.body.appendChild(el)}return el}
function preview(type){const p=S[type];if(!p)return;const el=overlay('my60VarietySheet','my60-vsheet');el.innerHTML='<div class="my60-vinner"><div class="my60-vtop"><div><span>'+esc(cats[p.cat])+'</span><h3>'+esc(p.title)+'</h3><p>'+esc(p.sub)+' · '+duration(p)+' · '+esc(p.level)+'</p></div><button class="my60-vclose" onclick="My60Variety.close()">×</button></div><button class="my60-vstart" onclick="My60Variety.start(\''+type+'\')">Начать тренировку</button><div class="my60-vlist">'+p.items.map((id,i)=>{const x=X[id];return '<div class="my60-vitem"><b>'+(i+1)+'. '+esc(x.n)+'</b><span>'+esc(x.f)+'</span><small>'+esc(x.d)+'</small></div>'}).join('')+'</div></div>';el.hidden=false;document.body.classList.add('my60-workout-open')}
function close(){const a=document.getElementById('my60VarietySheet'),b=document.getElementById('my60VarietyPlayer');if(a)a.hidden=true;if(b)b.hidden=true;document.body.classList.remove('my60-workout-open');rerenderPanel()}
function start(type){if(!S[type])return;write({type,e:0});const s=document.getElementById('my60VarietySheet');if(s)s.hidden=true;renderPlayer()}
function resume(){const r=read();if(r&&S[r.type])renderPlayer()}
function renderPlayer(){const r=read();if(!r||!S[r.type])return;const p=S[r.type],e=Math.max(0,Math.min(r.e,p.items.length-1)),x=X[p.items[e]],el=overlay('my60VarietyPlayer','my60-vplayer'),pct=Math.round(e/p.items.length*100);r.e=e;write(r);el.hidden=false;document.body.classList.add('my60-workout-open');el.innerHTML='<div class="my60-vpinner"><div class="my60-vphead"><button onclick="My60Variety.close()">×</button><div><span>'+esc(p.title)+'</span><b>Упражнение '+(e+1)+' из '+p.items.length+'</b></div><button onclick="My60Variety.preview(\''+r.type+'\')">≡</button></div><div class="my60-vprogress"><i style="width:'+pct+'%"></i></div><section class="my60-vexercise"><span>'+esc(x.f)+'</span><h2>'+esc(x.n)+'</h2><div class="my60-vdose">'+esc(x.d)+'</div><div class="my60-vsteps">'+x.s.map((v,i)=>'<div class="my60-vstep"><i>'+(i+1)+'</i><p>'+esc(v)+'</p></div>').join('')+'</div><div class="my60-vtip"><b>Важно:</b> '+esc(x.t)+'</div><div class="my60-vfeel"><b>Что должно чувствоваться:</b> '+esc(x.feel)+'</div></section><div class="my60-vactions"><button onclick="My60Variety.back()">‹ Назад</button><button class="main" onclick="My60Variety.next()">'+(e===p.items.length-1?'Завершить тренировку ✓':'Упражнение выполнено ✓')+'</button><button onclick="My60Variety.skip()">Пропустить ›</button></div></div>'}
function back(){const r=read();if(!r)return;r.e=Math.max(0,r.e-1);write(r);renderPlayer()}
function skip(){next()}
function next(){const r=read();if(!r||!S[r.type])return;const p=S[r.type];if(r.e<p.items.length-1){r.e++;write(r);renderPlayer();return}finish(r.type)}
function finish(type){markDone(type);write(null);const el=overlay('my60VarietyPlayer','my60-vplayer'),p=S[type];el.hidden=false;el.innerHTML='<div class="my60-vpinner"><div class="my60-vfinish"><i>✓</i><h2>Готово</h2><p>'+esc(p.title)+' завершена. Отметка сохранена в сегодняшних тренировках.</p><button onclick="My60Variety.done()">Готово</button></div></div>'}
function done(){const el=document.getElementById('my60VarietyPlayer');if(el)el.hidden=true;document.body.classList.remove('my60-workout-open');rerenderPanel();if(window.My60Library&&typeof My60Library.finish==='function')My60Library.finish()}
function filter(cat){activeCat=cats[cat]?cat:'all';rerenderPanel()}
function has(type){return !!S[type]}

function patchLibrary(){if(patched||!window.My60Library)return false;patched=true;const oldPreview=My60Library.preview&&My60Library.preview.bind(My60Library),oldStart=My60Library.start&&My60Library.start.bind(My60Library),oldFilter=My60Library.filter&&My60Library.filter.bind(My60Library),oldFinish=My60Library.finish&&My60Library.finish.bind(My60Library);if(oldPreview)My60Library.preview=function(type){return S[type]?preview(type):oldPreview(type)};if(oldStart)My60Library.start=function(type){return S[type]?start(type):oldStart(type)};if(oldFilter)My60Library.filter=function(cat){const out=oldFilter(cat);setTimeout(()=>{ensurePanel();document.dispatchEvent(new CustomEvent('my60:workouts-ready'))},50);return out};if(oldFinish)My60Library.finish=function(){const out=oldFinish();setTimeout(()=>{ensurePanel();document.dispatchEvent(new CustomEvent('my60:workouts-ready'))},60);return out};return true}
function watchStudio(){const studio=document.getElementById('workoutStudio');if(!studio)return;new MutationObserver(()=>{clearTimeout(observerTimer);observerTimer=setTimeout(()=>{if(studio.querySelector('.my60-library2')&&!document.getElementById('my60Variety')){ensurePanel();document.dispatchEvent(new CustomEvent('my60:workouts-ready'))}},40)}).observe(studio,{childList:true,subtree:false})}
function boot(){style();window.My60Variety={preview,start,resume,close,next,back,skip,done,filter,has};let tries=0;const iv=setInterval(()=>{tries++;const a=patchLibrary(),b=ensurePanel();if((a&&b)||tries>40)clearInterval(iv)},150);watchStudio();document.addEventListener('my60:workouts-ready',()=>setTimeout(()=>{patchLibrary();ensurePanel()},60))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
